id: PD3F05D6D
initial_creation_type: input
source_metadata:
  title: Dodrupchen Jigme Trinle Özer Series
  language: en
  description: 'Texts by the First Dodrupchen, Jigme Trinle Özer (rdo grub ’jigs med
    phrin las ''od zer, 1745–1821), who was also known as Kunzang Shenpen (kun bzang
    gzhan phan):'
  volume:
    05142d252b0b4374a1efc9fc3082a037:
      title: Aspiration at the Moment of Death
      parent: Aspiration Prayers
    45a7bc1e585143a99d9a85b508efd967:
      title: Brief Dharmapālas Offering
      parent: Dharma Protectors
    74c5239c2531404d92942643b760e4b5:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Guru Rinpoche prayers
    fed3da644945418fb75909fa1adb8a5f:
      title: 'A Constant Stream of Blessings: A Prayer to the Eight Supreme Vidyādharas
        of India'
      parent: Lineage Prayers
    e1977874e8de4df78d4a11abd5083967:
      title: The Brief Ḍākinī Prayer
      parent: Lineage Prayers
    8efe2887b7444181b5e648398d8c27ab:
      title: The Source of Accomplishment, the Fruit of the Two-Fold Truth—A Prayer
        to the Wisdom Ḍākinī Dechen Gyalmo
      parent: Lineage Prayers
    9d84bd5b19434dfe8efa2d90e6cc70b3:
      title: 'The Excellent Path to Omniscience: The Dzogchen Preliminary Practice
        of Longchen Nyingtik'
      parent: Ngöndro
    e02bfd1d422440beab759d8ee05eda0a:
      title: 'The Excellent Path to Perfect Liberation: A Guidance Practice (Nedren)
        for the Dukngal Rangdrol (Natural Liberation of Suffering) Practice of the
        Great Compassionate One from the Longchen Nyingtik'
      parent: Practices
    5f32dc6a462b4b3cabb680f17c77f9b6:
      title: 'The Source of Abundant Merit: A Feast-Offering for the Secret Practice
        of the Great Compassionate One, Natural Liberation of Suffering from The Heart
        Essence of the Vast Expanse'
      parent: Practices
    be08a2aa35544df596bd06c6c10685bd:
      title: 'The Stairway to Great Bliss: A Method for Planting the Seed of Liberation
        in Animals'
      parent: Practices
    c247cd853e6a4a4191131f685e8461b8:
      title: Detailed Visualization of the Great Compassionate One’s Retinue
      parent: Sādhanas
    682dc2c06a724fc78be6a18d12081140:
      title: 'Highway of the Great Yoga: A Daily Practice for the Peaceful and Wrathful
        Deities of the Self-Liberated Wisdom Mind'
      parent: Sādhanas
created_at: '2022-02-28T23:00:39.689495'
last_modified_at: '2022-02-28T23:00:39.689501'
